export const langConfig = ["en", "ru", "fr"];

export const translationConfig = {
  en: {
    logo: "Where in the world?",
    searchPlaceholder: "Search for a country",
    filter: "Filter By Region",
    population: "Population",
    region: "Region",
    capital: "Capital",
    backBtn: "Back",
    nativeName: "Native Name",
    subregion: "Subregion",
    currencies: "Currencies",
    languages: "Languages",
    topLevelDomain: "Top Level Domain",
    borderCountries: "Border Countries",
    nothingFoundTitle: "Nothing found",
    nothingFoundSubtitle: "Change the filter or search value",
    errorMessageTitle: "Error",
    errorMessageSubtitle: "Refresh the page or visit later",
    pageNotFound: "Page Not Found",
  },
  ru: {
    logo: "Где в мире?",
    searchPlaceholder: "Пиоск по странам",
    filter: "Выбрать регион",
    population: "Население",
    region: "Регион",
    capital: "Столица",
    backBtn: "Назад",
    nativeName: "Местное название",
    subregion: "Субрегион",
    currencies: "Валюта",
    languages: "Язык",
    topLevelDomain: "Домен",
    borderCountries: "Соседние страны",
    nothingFoundTitle: "Ничего не найдено",
    nothingFoundSubtitle: "Измените фильтр или значение поиска",
    errorMessageTitle: "Ошибка",
    errorMessageSubtitle: "Обновите страницу или зайдите позже",
    pageNotFound: "Страница не найдена",
  },
  fr: {
    logo: "Où dans le monde?",
    searchPlaceholder: "Rechercher un pays",
    filter: "Filtrer Par Région",
    population: "Population",
    region: "Région",
    capital: "Capital",
    backBtn: "Arrière",
    nativeName: "Nom Natif",
    subregion: "Sous-Région",
    currencies: "Change",
    languages: "Langue",
    topLevelDomain: "Domaine",
    borderCountries: "Pays Frontaliers",
    nothingFoundTitle: "Rien trouvé",
    nothingFoundSubtitle: "Modifier le filtre ou la valeur de recherche",
    errorMessageTitle: "Erreur",
    errorMessageSubtitle: "Actualisez la page ou visitez plus tard",
    pageNotFound: "Page introuvable",
  },
};
